name: CentOS Linux

on:
  push:
    branches: [ master, dev ]
  pull_request:
    branches: [ master, dev ]

jobs:
  test:
    runs-on: ubuntu-20.04
    
    strategy:
      fail-fast: false
      matrix:
        tag: ['7.5.1804', '8.4.2105']

    container: centos:${{ matrix.tag }}

    steps:
      - run: yum -y update && yum -y install git
        if:  ${{ matrix.tag == '7.5.1804' }}

        # https://stackoverflow.com/questions/70926799/centos-through-vm-no-urls-in-mirrorlist
      - run: |
          sed -i 's/mirrorlist/#mirrorlist/g' /etc/yum.repos.d/CentOS-Linux-*
          sed -i 's|#baseurl=http://mirror.centos.org|baseurl=http://vault.centos.org|g' /etc/yum.repos.d/CentOS-Linux-*
          dnf -y update
          dnf -y install git
        if:  ${{ matrix.tag == '8.4.2105' }}

      - uses: actions/checkout@v2

      - run: bin/ndk-pkg --help
      - run: bin/ndk-pkg --version
      - run: bin/ndk-pkg --homedir
      - run: bin/ndk-pkg --homepage

      - run: bin/ndk-pkg ndkmanager ls-available

      - run: bin/ndk-pkg env

      - run: bin/ndk-pkg integrate zsh

      - run: bin/ndk-pkg update

      - run: bin/ndk-pkg search lib
      - run: bin/ndk-pkg search zlib

      - run: bin/ndk-pkg formula-repo list

      - run: bin/ndk-pkg formula view curl
      - run: bin/ndk-pkg formula view zlib --paging=never

      - run: bin/ndk-pkg info zlib
      - run: bin/ndk-pkg info zlib version
      - run: bin/ndk-pkg info zlib webpage
      - run: bin/ndk-pkg info zlib

      - run: bin/ndk-pkg depends zlib

      - run: bin/ndk-pkg homepage
      - run: bin/ndk-pkg homepage zlib

      - run: bin/ndk-pkg install zlib


      - run: bin/ndk-pkg tree zlib
      - run: bin/ndk-pkg pack zlib

      - run: bin/ndk-pkg target abis
      - run: bin/ndk-pkg target archs
      - run: bin/ndk-pkg target triples
      - run: bin/ndk-pkg target levels

      - run: bin/ndk-pkg ls-available
      - run: bin/ndk-pkg ls-installed
      - run: bin/ndk-pkg ls-outdated

      - run: bin/ndk-pkg is-available zlib
      - run: bin/ndk-pkg is-installed zlib
      - run: bin/ndk-pkg is-outdated zlib || echo 'not outdated'

      - run: bin/ndk-pkg uninstall zlib

      - run: bin/ndk-pkg fetch curl

      - run: bin/ndk-pkg upgrade @self
