name: ci workflow

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-16.04, ubuntu-18.04, ubuntu-20.04, macos-11.0, macos-10.15]

    runs-on: ${{ matrix.os }}

    env:
      HOMEBREW_NO_INSTALL_CLEANUP: set

    steps:
    - run: export -p

    - if:   matrix.os == 'macos-11.0'
      run:  brew install gnu-sed

    - run:  brew install automake autoconf libtool pkg-config make cmake meson gperf itstool tree lzip nasm doxygen protobuf xmlto

    - uses: actions/checkout@v2

    - run:  mv bin/ndk-pkg $(brew --prefix)/bin
    
    - run:  ndk-pkg version
    - run:  ndk-pkg update
    - run:  ndk-pkg install boost

  install:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-16.04, ubuntu-18.04, ubuntu-20.04, macos-11.0, macos-10.15]

    runs-on: ${{ matrix.os }}

    env:
      HOMEBREW_NO_INSTALL_CLEANUP: set

    steps:
    - name: install ndk-pkg via homebrew
      run: |
        brew tap leleliu008/fpliu
        brew install ndk-pkg

    - run: ndk-pkg --version
