name: workflow on ubuntu

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    env:
      LANG: C.UTF-8
      ANDROID_NDK_HOME: /home/runner/android-ndk-r21d

    steps:
    - uses: actions/checkout@v2
    
    - name: update apt-get
      run: sudo apt-get -y -o APT::Immediate-Configure=false update

    - name: install build tools via apt-get
      run: sudo apt-get -y -o APT::Immediate-Configure=false install automake autoconf libtool pkg-config make cmake meson ninja-build gcc g++ curl gawk sed grep unzip tar xz-utils gzip bzip2 lzip tree

    - name: install android-ndk
      run: |
        curl -LO https://dl.google.com/android/repository/android-ndk-r21d-linux-x86_64.zip
        unzip -q android-ndk-r21d-linux-x86_64.zip -d $HOME
        rm android-ndk-r21d-linux-x86_64.zip

    - name: install ndk-pkg
      run: |
        curl -LO https://raw.githubusercontent.com/leleliu008/ndk-pkg/master/bin/ndk-pkg
        chmod u+x ndk-pkg

    - name:  ndk-pkg --version
      run: ./ndk-pkg --version

    - name:  ndk-pkg update
      run: ./ndk-pkg update

    - name:  ndk-pkg install curl
      run: ./ndk-pkg install curl
