name: Ubuntu

on:
  push:
    branches: [ master, dev ]
  pull_request:
    branches: [ master, dev ]

jobs:
  test:

    strategy:
      fail-fast: false
      matrix:
        version: [18.04, 20.04]

    runs-on: ubuntu-${{ matrix.version }}

    steps:
      - uses: actions/checkout@v2

      - run: bin/ndk-pkg --help
      - run: bin/ndk-pkg --version
      - run: bin/ndk-pkg --homedir
      - run: bin/ndk-pkg --homepage

      - run: bin/ndk-pkg ndkmanager ls-available

      - run: bin/ndk-pkg env

      - run: bin/ndk-pkg integrate zsh

      - run: bin/ndk-pkg update

      - run: git -C ~/.ndk-pkg/repos.d/offical checkout ${{ github.ref_name }}

      - run: bin/ndk-pkg search lib
      - run: bin/ndk-pkg search zlib

      - run: bin/ndk-pkg formula-repo list

      - run: bin/ndk-pkg formula view curl
      - run: bin/ndk-pkg formula view zlib --paging=never

      - run: bin/ndk-pkg info zlib
      - run: bin/ndk-pkg info zlib version
      - run: bin/ndk-pkg info zlib webpage
      - run: bin/ndk-pkg info zlib

      - run: bin/ndk-pkg depends zlib

      - run: bin/ndk-pkg homepage
      - run: bin/ndk-pkg homepage zlib

      - run: bin/ndk-pkg install zlib


      - run: bin/ndk-pkg tree zlib
      - run: bin/ndk-pkg pack zlib

      - run: bin/ndk-pkg ls-target-abis
      - run: bin/ndk-pkg ls-target-archs
      - run: bin/ndk-pkg ls-target-triples
      - run: bin/ndk-pkg ls-target-levels

      - run: bin/ndk-pkg ls-available
      - run: bin/ndk-pkg ls-installed
      - run: bin/ndk-pkg ls-outdated

      - run: bin/ndk-pkg is-available zlib
      - run: bin/ndk-pkg is-installed zlib
      - run: bin/ndk-pkg is-outdated  zlib || echo "not outdated"

      - run: bin/ndk-pkg uninstall zlib

      - run: bin/ndk-pkg fetch curl

      - run: bin/ndk-pkg upgrade @self

  install_via_homebrew:

    strategy:
      fail-fast: false
      matrix:
        version: [18.04, 20.04]

    runs-on: ubuntu-${{ matrix.version }}

    steps:
      - run: brew tap leleliu008/fpliu
      - run: brew install ndk-pkg

      - run: ndk-pkg --help
      - run: ndk-pkg --version
      - run: ndk-pkg --homedir
      - run: ndk-pkg --homepage

      - run: ndk-pkg env

      - run: ndk-pkg integrate zsh

      - run: ndk-pkg update

      - run: ndk-pkg search lib
      - run: ndk-pkg search zlib

      - run: ndk-pkg info zlib
      - run: ndk-pkg info zlib version
      - run: ndk-pkg info zlib webpage
      - run: ndk-pkg info zlib

      - run: ndk-pkg depends zlib

      - run: ndk-pkg homepage
      - run: ndk-pkg homepage zlib

      - run: ndk-pkg install zlib

      - run: ndk-pkg tree zlib
      - run: ndk-pkg pack zlib

      - run: ndk-pkg formula-repo list
      - run: ndk-pkg formula view curl

      - run: ndk-pkg ls-target-abis
      - run: ndk-pkg ls-target-archs
      - run: ndk-pkg ls-target-triples
      - run: ndk-pkg ls-target-levels

      - run: ndk-pkg ls-available
      - run: ndk-pkg ls-installed
      - run: ndk-pkg ls-outdated

      - run: ndk-pkg is-available zlib
      - run: ndk-pkg is-installed zlib
      - run: ndk-pkg is-outdated  zlib || echo "not outdated"

      - run: ndk-pkg uninstall zlib

      - run: ndk-pkg fetch curl

      - run: ndk-pkg upgrade @self
