name: WSL

on:
  push:
    branches: [ master, dev ]
  pull_request:
    branches: [ master, dev ]

jobs:
  testing:
    runs-on: windows-latest

    strategy:
      fail-fast: false
      matrix:
        distribution: [Ubuntu-20.04, Debian, openSUSE-Leap-15.2]

    defaults:
      run:
        shell: wsl-bash {0}

    steps:
      # https://github.com/marketplace/actions/setup-wsl
      - uses: Vampire/setup-wsl@v1
        with:
          distribution: ${{ matrix.distribution }}

      - name: Use unix line endings
        shell: bash
        run: |
          # Github's actions/checkout@v2 when run on Windows mangles the line-endings to DOS-style
          # but we're running Linux *on top* of Windows, so we need to not mangle them!
          # https://github.com/actions/checkout/issues/135#issuecomment-602171132
          # https://github.com/actions/virtual-environments/issues/50#issuecomment-663920265
          git config --global core.autocrlf false
          git config --global core.eol lf

      - uses: actions/checkout@v2

      - run: bin/ndk-pkg --help
      - run: bin/ndk-pkg --version
      - run: bin/ndk-pkg --homedir
      - run: bin/ndk-pkg --homepage

      - run: bin/ndk-pkg ndkmanager ls-available

      - run: bin/ndk-pkg env

      - run: bin/ndk-pkg integrate zsh

      - run: bin/ndk-pkg update

      - run: git -C ~/.ndk-pkg/repos.d/offical checkout ${{ github.ref_name }}

      - run: bin/ndk-pkg search lib
      - run: bin/ndk-pkg search zlib

      - run: bin/ndk-pkg info zlib
      - run: bin/ndk-pkg info zlib version
      - run: bin/ndk-pkg info zlib webpage
      - run: bin/ndk-pkg info zlib

      - run: bin/ndk-pkg depends zlib

      - run: bin/ndk-pkg homepage
      - run: bin/ndk-pkg homepage zlib

      - run: bin/ndk-pkg install zlib


      - run: bin/ndk-pkg tree zlib

      - run: bin/ndk-pkg pack zlib tar.gz
      - run: bin/ndk-pkg pack zlib tar.xz
      - run: bin/ndk-pkg pack zlib tar.bz2
      - run: bin/ndk-pkg pack zlib 7z
      - run: bin/ndk-pkg pack zlib zip
      - run: bin/ndk-pkg pack zlib aar

      - run: bin/ndk-pkg formula-repo list
      - run: bin/ndk-pkg formula view curl

      - run: bin/ndk-pkg ls-target-abis
      - run: bin/ndk-pkg ls-target-archs
      - run: bin/ndk-pkg ls-target-triples
      - run: bin/ndk-pkg ls-target-levels

      - run: bin/ndk-pkg ls-available
      - run: bin/ndk-pkg ls-installed
      - run: bin/ndk-pkg ls-outdated

      - run: bin/ndk-pkg is-available zlib
      - run: bin/ndk-pkg is-installed zlib
      - run: bin/ndk-pkg is-outdated zlib || echo "not outdated"

      - run: bin/ndk-pkg uninstall zlib

      - run: bin/ndk-pkg fetch curl

      - run: bin/ndk-pkg upgrade @self
